# Generated by Django 4.1.4 on 2022-12-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='answer_text',
        ),
    ]
