# Generated by Django 4.1.4 on 2022-12-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_question_text_question_answer_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
